---
name: Pull Request Labeler
on:
  - pull_request_target

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
      - uses: actions/labeler@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e # tag=v4.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
